/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	F:/al_data/H10_CK203_PH2A180/new/2/IMX415_UDP/uisrc/03_ip/alip/pll.v
 ** Date	:	2025 11 05
 ** TD version	:	6.2.175876
************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:                25.000000MHz
//	Clock multiplication factor: 70
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 125.000000MHZ	| 0.0000  DEG  
//		C1        	| 125.000000MHZ	| 90.0000 DEG  
//		C2        	| 70.000000 MHZ	| 0.0000  DEG  
//		C3        	| 23.972603 MHZ	| 0.0000  DEG  
//		C4        	| 35.714286 MHZ	| 0.0000  DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll (
  refclk,
  lock,
  clk0_out,
  clk1_out,
  clk2_out,
  clk3_out,
  clk4_out 
);

  input refclk;
  output lock;
  output clk0_out;
  output clk1_out;
  output clk2_out;
  output clk3_out;
  output clk4_out;

  wire clk0_buf;
  wire clk1_buf;
  wire clk3_buf;

  PH1_LOGIC_BUFG bufg_c0 (
    .i(clk0_buf),
    .o(clk0_out) 
  );

  PH1_LOGIC_BUFG bufg_c1 (
    .i(clk1_buf),
    .o(clk1_out) 
  );

  PH1_LOGIC_BUFG bufg_c3 (
    .i(clk3_buf),
    .o(clk3_out) 
  );

  PH1_PHY_PLL #(
    .DYN_PHASE_PATH_SEL("DISABLE"),
    .DYN_FPHASE_EN("DISABLE"),
    .MPHASE_ENABLE("DISABLE"),
    .FIN("25.000000"),
    .FEEDBK_MODE("NOCOMP"),
    .FBKCLK("VCO_PHASE0"),
    .FBKCLK_INT("VCO_PHASE0"),
    .PLL_FEED_TYPE("INTERNAL"),
    .PLL_USR_RST("DISABLE"),
    .GMC_GAIN(1),
    .ICP_CUR(11),
    .LPF_CAP(2),
    .LPF_RES(3),
    .REFCLK_DIV(1),
    .FBCLK_DIV(70),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_DIV(14),
    .CLKC0_CPHASE(13),
    .CLKC0_FPHASE(0),
    .CLKC0_FPHASE_RSTSEL(0),
    .CLKC0_DUTY_INT(7),
    .CLKC0_DUTY50("ENABLE"),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(14),
    .CLKC1_CPHASE(2),
    .CLKC1_FPHASE(4),
    .CLKC1_FPHASE_RSTSEL(1),
    .CLKC1_DUTY_INT(7),
    .CLKC1_DUTY50("ENABLE"),
    .CLKC2_ENABLE("ENABLE"),
    .CLKC2_DIV(25),
    .CLKC2_CPHASE(24),
    .CLKC2_FPHASE(0),
    .CLKC2_FPHASE_RSTSEL(0),
    .CLKC2_DUTY_INT(13),
    .CLKC2_DUTY50("ENABLE"),
    .CLKC3_ENABLE("ENABLE"),
    .CLKC3_DIV(73),
    .CLKC3_CPHASE(72),
    .CLKC3_FPHASE(0),
    .CLKC3_FPHASE_RSTSEL(0),
    .CLKC3_DUTY_INT(37),
    .CLKC3_DUTY50("ENABLE"),
    .CLKC4_ENABLE("ENABLE"),
    .CLKC4_DIV(49),
    .CLKC4_CPHASE(48),
    .CLKC4_FPHASE(0),
    .CLKC4_FPHASE_RSTSEL(0),
    .CLKC4_DUTY_INT(25),
    .CLKC4_DUTY50("ENABLE"),
    .INTPI(2),
    .HIGH_SPEED_EN("DISABLE"),
    .SSC_ENABLE("DISABLE"),
    .SSC_MODE("CENTER"),
    .SSC_AMP(0.0000),
    .SSC_FREQ_DIV(0),
    .SSC_RNGE(0),
    .FRAC_ENABLE("DISABLE"),
    .DITHER_ENABLE("DISABLE"),
    .SDM_FRAC(0) 
  ) pll_inst (
    .refclk(refclk),
    .pllreset(1'b0),
    .lock(lock),
    .pllpd(1'b0),
    .refclk_rst(1'b0),
    .wakeup(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(pll_open0),
    .cps_step(2'b00),
    .drp_clk(1'b0),
    .drp_rstn(1'b1),
    .drp_sel(1'b0),
    .drp_rd(1'b0),
    .drp_wr(1'b0),
    .drp_addr(8'b00000000),
    .drp_wdata(8'b00000000),
    .drp_err(pll_open1),
    .drp_rdy(pll_open2),
    .drp_rdata({pll_open10, pll_open9, pll_open8, pll_open7, pll_open6, pll_open5, pll_open4, pll_open3}),
    .fbclk(1'b0),
    .clkc({pll_open20, pll_open18, pll_open16, clk4_out, clk3_buf, clk2_out, clk1_buf, clk0_buf}),
    .clkcb({pll_open21, pll_open19, pll_open17, pll_open15, pll_open14, pll_open13, pll_open12, pll_open11}),
    .clkc_en({8'b00011111}),
    .clkc_rst(2'b00),
    .ext_freq_mod_clk(1'b0),
    .ext_freq_mod_en(1'b0),
    .ext_freq_mod_val(17'b00000000000000000),
    .ssc_en(1'b0) 
  );

endmodule

