/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/test/08_mipi_1080p_lvds_hdmi_f201-2/uisrc/03_ip/alip/w32_d962_shifter.v
 ** Date	:	2023 06 08
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module w32_d962_shifter(dataout,
	clk, en, datain);

    input                     clk;
    input                     en;
    input       [31:0]      datain;
    output      [31:0]      dataout;
    PH1_LOGIC_SHIFTER#(
        .DATA_WIDTH(32),
        .DATA_DEPTH(482),
        .INIT_FILE("NONE"),
        .SHIFT_TYPE("FIXED"))
        inst(
         .depth({1{1'b0}}),
         .dataout(dataout),
         .clk(clk),
         .en(en),
         .datain(datain));

endmodule
