/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/project/my_project/I___Anlogic___camera__imx334_to_hdmi_display_4kp30____PH1A90/user_source/ip_source/w40_d512_fifo.v
 ** Date	:	2022 10 14
 ** TD version	:	5.6.60427
\************************************************************/

`timescale 1ns / 1ps

module w40_d512_fifo (
	rst,
	di, re, clk, we,
	dout,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [39:0] di;
	input clk, we;
	input re;

	output [39:0] dout;
	output empty_flag;
	output full_flag;
	output [9:0] rdusedw;
	output [9:0] wrusedw;

PH1_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(40),
	.ADDR_WIDTH(9),
	.SHOWAHEAD(0),
	.IMPLEMENT("20K")
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clk(clk),
	.we(we),
	.dout(dout),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule