--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/project/my_project/I___Anlogic___camera__imx334_to_hdmi_display_4kp30____PH1A90/user_source/ip_source/w40_d512_fifo.vhd
 -- Date	:	2022 10 14
 -- TD version	:	5.6.60427
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY w40_d512_fifo IS
PORT (
	di	: IN STD_LOGIC_VECTOR(39 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	dout	: OUT STD_LOGIC_VECTOR(39 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(9 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(9 DOWNTO 0)
	);
END w40_d512_fifo;

ARCHITECTURE struct OF w40_d512_fifo IS

	BEGIN
	inst : PH1_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 40,
			ADDR_WIDTH			=> 9,
			SHOWAHEAD			=> 0,
			IMPLEMENT			=>"20K"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			dout	=> dout,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
